[project]
name = "bullet-journal"
version = "1.2.2"
description = "A local-first Bullet Journal application with graphical and command-line interfaces using Markdown files."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.urls]
Repository = "https://github.com/psierrajs/bullet-journal"

[tool.unittest]
start-directory = "."
pattern = "test_*.py"

[project.scripts]
bullet-journal = "bullet_journal.app:main"
bullet-journal-gui = "bullet_journal.gui:main"

[tool.setuptools]
packages = ["bullet_journal"]